package model;

public enum MetroEventsEnum {
    //All possible events
    OPEN_METROSTATION,
    BUY_NEW_METROCARD,
    BUY_METROCARD_TICKETS,
    SCAN_METROGATE,
    OPEN_METROGATE,
    METROCARD_SCANNED, 
    METROGATE_OPENED, 
    CLOSE_METROGATE, 
    ACTIVATE_METROGATE, 
    DEACTIVATE_METROGATE,
    ALERT

}
